{
 "title": "SmartSauna",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(timestamp) AS \"time\",\n  percentage\nFROM humidity\nWHERE\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\n   UNIX_TIMESTAMP(timestamp) AS \"time\",\n  degrees\nFROM temperature\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Presence",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(timestamp) AS \"time\",\n  quantity\nFROM presence\nWHERE\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Air Quality",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(timestamp) AS \"time\",\n  concentration\nFROM air_quality\nWHERE\n  $__timeFilter(timestamp) \n  AND node = 2\nORDER BY timestamp"
    },
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(timestamp) AS \"time\",\n  concentration\nFROM air_quality\nWHERE\n  $__timeFilter(timestamp) \n  AND node = 3\nORDER BY timestamp"
    }
   ]
  }
 ]
}